invalid_skills = [
    "are",
    "management",
    "regulation",
    "tracking",
    "linkedin",
    "gitHub",
    "processing",
    # "pyspark",  # This can be a skill / tools / framework
    "federal",
    "technologies",
    "uat",
    "system",
    "compliance",
    "basic",
    "engineering",
    "numbers",
    "hive",
    "party",
    "support",
    "incident",
    "Spark",
    "scripting",
    "contract",
    "requirement gathering",
    "tuning",
    "interaction",
    "will",
    "process",
    "retail",
    "number",
    "performance tuning",
    "report",
    "management",
    "tuning",
    "logic",
    "systems",
    "policy",
    "inventory",
    "life insurance",
    "Part",
    "scheduling",
    "responsible",
    "handling",
    "authentication",
    "history",
    "map",
    "recovery",
    "will",
    "p",
    "feature",
    "reports",
    "Textile industry",
    "law enforcement",
    "work independently",
    "employee",
    "access",
    "attention to detail",
    "logic",
    "entity framework",
    "accreditation",
    "flexible approach",
    "commission" "refining",
    "implementing",
    "code coverage",
    "structure",
    "calculations",
    "l",
    "release notes",
    "pricing",
    "regulatory",
    "testrail",
    "workflow",
    "investment",
]
